version: '3.8'

volumes:
  orderer.nitw.edu:
  peer0.nit.edu:
  peer1.nit.edu:
  peer0.dept.nit.edu:
  peer1.dept.nit.edu:
  peer0.verifiers.nit.edu:

networks:
  academic-records:
    driver: bridge

services:
  # ====== ORDERER SERVICE ======
  orderer.nitw.edu:
    container_name: orderer.nitw.edu
    image: hyperledger/fabric-orderer:latest
    labels:
      service: hyperledger-fabric
    environment:
      - FABRIC_LOGGING_SPEC=INFO
      - ORDERER_GENERAL_LISTENADDRESS=0.0.0.0
      - ORDERER_GENERAL_LISTENPORT=7050
      - ORDERER_GENERAL_GENESISMETHOD=file
      - ORDERER_GENERAL_GENESISFILE=/var/hyperledger/orderer/orderer.genesis.block
      - ORDERER_GENERAL_LOCALMSPID=OrdererMSP
      - ORDERER_GENERAL_LOCALMSPDIR=/var/hyperledger/orderer/msp
      - ORDERER_GENERAL_TLS_ENABLED=true
      - ORDERER_GENERAL_TLS_PRIVATEKEY=/var/hyperledger/orderer/tls/server.key
      - ORDERER_GENERAL_TLS_CERTIFICATE=/var/hyperledger/orderer/tls/server.crt
      - ORDERER_GENERAL_TLS_ROOTCAS=[/var/hyperledger/orderer/tls/ca.crt]
      - ORDERER_GENERAL_CLUSTER_LISTENADDRESS=0.0.0.0
      - ORDERER_GENERAL_CLUSTER_LISTENPORT=7051
      - ORDERER_GENERAL_CLUSTER_CLIENTCERTIFICATE=/var/hyperledger/orderer/tls/server.crt
      - ORDERER_GENERAL_CLUSTER_CLIENTPRIVATEKEY=/var/hyperledger/orderer/tls/server.key
      - ORDERER_GENERAL_CLUSTER_ROOTCAS=[/var/hyperledger/orderer/tls/ca.crt]
      - ORDERER_GENERAL_BOOTSTRAPMETHOD=none
      - ORDERER_CHANNELPARTICIPATION_ENABLED=true
      - ORDERER_ADMIN_LISTENADDRESS=0.0.0.0:7053
      - ORDERER_OPERATIONS_LISTENADDRESS=0.0.0.0:9443
    working_dir: /opt/gopath/src/github.com/hyperledger/fabric
    command: orderer
    volumes:
      - ../organizations/ordererOrganizations/orderer.nitw.edu/orderers/orderer.nitw.edu/msp:/var/hyperledger/orderer/msp
      - ../organizations/ordererOrganizations/orderer.nitw.edu/orderers/orderer.nitw.edu/tls:/var/hyperledger/orderer/tls
      - ../system-genesis-block/genesis.block:/var/hyperledger/orderer/orderer.genesis.block
      - orderer.nitw.edu:/var/hyperledger/production/orderer
    ports:
      - "7050:7050"
      - "7053:7053"
      - "9443:9443"
    networks:
      - academic-records

  # ====== NITWARANGAL ORGANIZATION - PEER 0 ======
  peer0.nit.edu:
    container_name: peer0.nit.edu
    image: hyperledger/fabric-peer:latest
    labels:
      service: hyperledger-fabric
    environment:
      - FABRIC_CFG_PATH=/etc/hyperledger/peercfg
      - FABRIC_LOGGING_SPEC=INFO
      - CORE_PEER_TLS_ENABLED=true
      - CORE_PEER_PROFILE_ENABLED=true
      - CORE_PEER_TLS_CERT_FILE=/etc/hyperledger/fabric/tls/server.crt
      - CORE_PEER_TLS_KEY_FILE=/etc/hyperledger/fabric/tls/server.key
      - CORE_PEER_TLS_ROOTCERT_FILE=/etc/hyperledger/fabric/tls/ca.crt
      - CORE_PEER_ID=peer0.nit.edu
      - CORE_PEER_ADDRESS=peer0.nit.edu:7051
      - CORE_PEER_LISTENADDRESS=0.0.0.0:7051
      - CORE_PEER_CHAINCODEADDRESS=peer0.nit.edu:7052
      - CORE_PEER_CHAINCODELISTENADDRESS=0.0.0.0:7052
      - CORE_PEER_GOSSIP_BOOTSTRAP=peer1.nit.edu:8051
      - CORE_PEER_GOSSIP_EXTERNALENDPOINT=peer0.nit.edu:7051
      - CORE_PEER_LOCALMSPID=NITWarangalMSP
      - CORE_PEER_MSPCONFIGPATH=/etc/hyperledger/fabric/msp
      - CORE_OPERATIONS_LISTENADDRESS=0.0.0.0:9440
    volumes:
      - ../organizations/peerOrganizations/nit.edu/peers/peer0.nit.edu/msp:/etc/hyperledger/fabric/msp
      - ../organizations/peerOrganizations/nit.edu/peers/peer0.nit.edu/tls:/etc/hyperledger/fabric/tls
      - peer0.nit.edu:/var/hyperledger/production
      - ../config/core.yaml:/etc/hyperledger/peercfg/core.yaml
    working_dir: /opt/gopath/src/github.com/hyperledger/fabric/peer
    command: peer node start
    ports:
      - "7051:7051"
      - "9440:9440"
    networks:
      - academic-records

  # ====== NITWARANGAL ORGANIZATION - PEER 1 ======
  peer1.nit.edu:
    container_name: peer1.nit.edu
    image: hyperledger/fabric-peer:latest
    labels:
      service: hyperledger-fabric
    environment:
      - FABRIC_CFG_PATH=/etc/hyperledger/peercfg
      - FABRIC_LOGGING_SPEC=INFO
      - CORE_PEER_TLS_ENABLED=true
      - CORE_PEER_PROFILE_ENABLED=true
      - CORE_PEER_TLS_CERT_FILE=/etc/hyperledger/fabric/tls/server.crt
      - CORE_PEER_TLS_KEY_FILE=/etc/hyperledger/fabric/tls/server.key
      - CORE_PEER_TLS_ROOTCERT_FILE=/etc/hyperledger/fabric/tls/ca.crt
      - CORE_PEER_ID=peer1.nit.edu
      - CORE_PEER_ADDRESS=peer1.nit.edu:8051
      - CORE_PEER_LISTENADDRESS=0.0.0.0:8051
      - CORE_PEER_CHAINCODEADDRESS=peer1.nit.edu:8052
      - CORE_PEER_CHAINCODELISTENADDRESS=0.0.0.0:8052
      - CORE_PEER_GOSSIP_BOOTSTRAP=peer0.nit.edu:7051
      - CORE_PEER_GOSSIP_EXTERNALENDPOINT=peer1.nit.edu:8051
      - CORE_PEER_LOCALMSPID=NITWarangalMSP
      - CORE_PEER_MSPCONFIGPATH=/etc/hyperledger/fabric/msp
      - CORE_OPERATIONS_LISTENADDRESS=0.0.0.0:9441
    volumes:
      - ../organizations/peerOrganizations/nit.edu/peers/peer1.nit.edu/msp:/etc/hyperledger/fabric/msp
      - ../organizations/peerOrganizations/nit.edu/peers/peer1.nit.edu/tls:/etc/hyperledger/fabric/tls
      - peer1.nit.edu:/var/hyperledger/production
      - ../config/core.yaml:/etc/hyperledger/peercfg/core.yaml
    working_dir: /opt/gopath/src/github.com/hyperledger/fabric/peer
    command: peer node start
    ports:
      - "8051:8051"
      - "9441:9441"
    networks:
      - academic-records

  # ====== DEPARTMENTS ORGANIZATION - PEER 0 ======
  peer0.dept.nit.edu:
    container_name: peer0.dept.nit.edu
    image: hyperledger/fabric-peer:latest
    labels:
      service: hyperledger-fabric
    environment:
      - FABRIC_CFG_PATH=/etc/hyperledger/peercfg
      - FABRIC_LOGGING_SPEC=INFO
      - CORE_PEER_TLS_ENABLED=true
      - CORE_PEER_PROFILE_ENABLED=true
      - CORE_PEER_TLS_CERT_FILE=/etc/hyperledger/fabric/tls/server.crt
      - CORE_PEER_TLS_KEY_FILE=/etc/hyperledger/fabric/tls/server.key
      - CORE_PEER_TLS_ROOTCERT_FILE=/etc/hyperledger/fabric/tls/ca.crt
      - CORE_PEER_ID=peer0.dept.nit.edu
      - CORE_PEER_ADDRESS=peer0.dept.nit.edu:9051
      - CORE_PEER_LISTENADDRESS=0.0.0.0:9051
      - CORE_PEER_CHAINCODEADDRESS=peer0.dept.nit.edu:9052
      - CORE_PEER_CHAINCODELISTENADDRESS=0.0.0.0:9052
      - CORE_PEER_GOSSIP_BOOTSTRAP=peer1.dept.nit.edu:10051
      - CORE_PEER_GOSSIP_EXTERNALENDPOINT=peer0.dept.nit.edu:9051
      - CORE_PEER_LOCALMSPID=DepartmentsMSP
      - CORE_PEER_MSPCONFIGPATH=/etc/hyperledger/fabric/msp
      - CORE_OPERATIONS_LISTENADDRESS=0.0.0.0:9442
    volumes:
      - ../organizations/peerOrganizations/dept.nit.edu/peers/peer0.dept.nit.edu/msp:/etc/hyperledger/fabric/msp
      - ../organizations/peerOrganizations/dept.nit.edu/peers/peer0.dept.nit.edu/tls:/etc/hyperledger/fabric/tls
      - peer0.dept.nit.edu:/var/hyperledger/production
      - ../config/core.yaml:/etc/hyperledger/peercfg/core.yaml
    working_dir: /opt/gopath/src/github.com/hyperledger/fabric/peer
    command: peer node start
    ports:
      - "9051:9051"
      - "9442:9442"
    networks:
      - academic-records

  # ====== DEPARTMENTS ORGANIZATION - PEER 1 ======
  peer1.dept.nit.edu:
    container_name: peer1.dept.nit.edu
    image: hyperledger/fabric-peer:latest
    labels:
      service: hyperledger-fabric
    environment:
      - FABRIC_CFG_PATH=/etc/hyperledger/peercfg
      - FABRIC_LOGGING_SPEC=INFO
      - CORE_PEER_TLS_ENABLED=true
      - CORE_PEER_PROFILE_ENABLED=true
      - CORE_PEER_TLS_CERT_FILE=/etc/hyperledger/fabric/tls/server.crt
      - CORE_PEER_TLS_KEY_FILE=/etc/hyperledger/fabric/tls/server.key
      - CORE_PEER_TLS_ROOTCERT_FILE=/etc/hyperledger/fabric/tls/ca.crt
      - CORE_PEER_ID=peer1.dept.nit.edu
      - CORE_PEER_ADDRESS=peer1.dept.nit.edu:10051
      - CORE_PEER_LISTENADDRESS=0.0.0.0:10051
      - CORE_PEER_CHAINCODEADDRESS=peer1.dept.nit.edu:10052
      - CORE_PEER_CHAINCODELISTENADDRESS=0.0.0.0:10052
      - CORE_PEER_GOSSIP_BOOTSTRAP=peer0.dept.nit.edu:9051
      - CORE_PEER_GOSSIP_EXTERNALENDPOINT=peer1.dept.nit.edu:10051
      - CORE_PEER_LOCALMSPID=DepartmentsMSP
      - CORE_PEER_MSPCONFIGPATH=/etc/hyperledger/fabric/msp
      - CORE_OPERATIONS_LISTENADDRESS=0.0.0.0:9443
    volumes:
      - ../organizations/peerOrganizations/dept.nit.edu/peers/peer1.dept.nit.edu/msp:/etc/hyperledger/fabric/msp
      - ../organizations/peerOrganizations/dept.nit.edu/peers/peer1.dept.nit.edu/tls:/etc/hyperledger/fabric/tls
      - peer1.dept.nit.edu:/var/hyperledger/production
      - ../config/core.yaml:/etc/hyperledger/peercfg/core.yaml
    working_dir: /opt/gopath/src/github.com/hyperledger/fabric/peer
    command: peer node start
    ports:
      - "10051:10051"
      - "9443:9443"
    networks:
      - academic-records

  # ====== VERIFIERS ORGANIZATION - PEER 0 ======
  peer0.verifiers.nit.edu:
    container_name: peer0.verifiers.nit.edu
    image: hyperledger/fabric-peer:latest
    labels:
      service: hyperledger-fabric
    environment:
      - FABRIC_CFG_PATH=/etc/hyperledger/peercfg
      - FABRIC_LOGGING_SPEC=INFO
      - CORE_PEER_TLS_ENABLED=true
      - CORE_PEER_PROFILE_ENABLED=true
      - CORE_PEER_TLS_CERT_FILE=/etc/hyperledger/fabric/tls/server.crt
      - CORE_PEER_TLS_KEY_FILE=/etc/hyperledger/fabric/tls/server.key
      - CORE_PEER_TLS_ROOTCERT_FILE=/etc/hyperledger/fabric/tls/ca.crt
      - CORE_PEER_ID=peer0.verifiers.nit.edu
      - CORE_PEER_ADDRESS=peer0.verifiers.nit.edu:11051
      - CORE_PEER_LISTENADDRESS=0.0.0.0:11051
      - CORE_PEER_CHAINCODEADDRESS=peer0.verifiers.nit.edu:11052
      - CORE_PEER_CHAINCODELISTENADDRESS=0.0.0.0:11052
      - CORE_PEER_GOSSIP_BOOTSTRAP=peer0.verifiers.nit.edu:11051
      - CORE_PEER_GOSSIP_EXTERNALENDPOINT=peer0.verifiers.nit.edu:11051
      - CORE_PEER_LOCALMSPID=VerifiersMSP
      - CORE_PEER_MSPCONFIGPATH=/etc/hyperledger/fabric/msp
      - CORE_OPERATIONS_LISTENADDRESS=0.0.0.0:9444
    volumes:
      - ../organizations/peerOrganizations/verifiers.nit.edu/peers/peer0.verifiers.nit.edu/msp:/etc/hyperledger/fabric/msp
      - ../organizations/peerOrganizations/verifiers.nit.edu/peers/peer0.verifiers.nit.edu/tls:/etc/hyperledger/fabric/tls
      - peer0.verifiers.nit.edu:/var/hyperledger/production
      - ../config/core.yaml:/etc/hyperledger/peercfg/core.yaml
    working_dir: /opt/gopath/src/github.com/hyperledger/fabric/peer
    command: peer node start
    ports:
      - "11051:11051"
      - "9444:9444"
    networks:
      - academic-records
